/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/namifax/templates/**/*.jinja2",
    "./src/namifax/views/**/*.py",
  ],
  theme: {
    extend: {
      colors: {
        // Google Material Design 3 (M3) Baseline Light Theme (User Portal)
        m3: {
          primary: '#005ac1',
          'on-primary': '#ffffff',
          'primary-container': '#d8e2ff',
          'on-primary-container': '#001a41',
          secondary: '#575e71',
          'on-secondary': '#ffffff',
          'secondary-container': '#dbe2f9',
          'on-secondary-container': '#141b2c',
          tertiary: '#715573',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#fbd7fc',
          'on-tertiary-container': '#29132d',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#410002',
          surface: '#fdfcff',
          'on-surface': '#1a1b1f',
          'surface-dim': '#ded8e1',
          'surface-bright': '#fef7ff',
          'surface-variant': '#e1e2ec',
          'on-surface-variant': '#44474f',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f7f2fa',
          'surface-container': '#f1f3f8',
          'surface-container-high': '#ece6f0',
          'surface-container-highest': '#e2e2e9',
          outline: '#74777f',
          'outline-variant': '#c4c6d0',
          'inverse-surface': '#2f3033',
          'inverse-on-surface': '#f1f0f4',
          'inverse-primary': '#a8c7fa',

          // Google Material Design 3 (M3) Dark Theme (Admin Appliance Console)
          dark: {
            primary: '#a8c7fa',
            'on-primary': '#002f65',
            'primary-container': '#0842a0',
            'on-primary-container': '#d8e2ff',
            secondary: '#bfc6dc',
            'on-secondary': '#293041',
            'secondary-container': '#3f4759',
            'on-secondary-container': '#dbe2f9',
            tertiary: '#dfbbde',
            'on-tertiary': '#402843',
            'tertiary-container': '#583e5a',
            'on-tertiary-container': '#fbd7fc',
            error: '#ffb4ab',
            'on-error': '#690005',
            'error-container': '#93000a',
            'on-error-container': '#ffdad6',
            surface: '#111318',
            'on-surface': '#e2e2e6',
            'surface-dim': '#111318',
            'surface-bright': '#37393e',
            'surface-variant': '#44474f',
            'on-surface-variant': '#c4c6cf',
            'surface-container-lowest': '#0c0e13',
            'surface-container-low': '#191c20',
            'surface-container': '#1d2024',
            'surface-container-high': '#282a2f',
            'surface-container-highest': '#33353a',
            outline: '#8e9099',
            'outline-variant': '#44474f',
            'inverse-surface': '#e2e2e6',
            'inverse-on-surface': '#2f3033',
            'inverse-primary': '#005ac1',
          }
        },
        // 레거시 브릿징 컬러
        af: {
          blue: '#005ac1',
          'blue-dark': '#004394',
          'blue-light': '#d8e2ff',
          red: '#ba1a1a',
          gray: '#f1f3f8',
          border: '#c4c6d0',
          line: '#74777f',
        }
      },
      borderRadius: {
        'm3-none': '0px',
        'm3-xs': '4px',
        'm3-sm': '8px',
        'm3-md': '12px',
        'm3-lg': '16px',
        'm3-xl': '28px',
        'm3-full': '9999px',
      },
      boxShadow: {
        '2xs': '0 1px 2px 0 rgba(0, 0, 0, 0.04)',
        'm3-1': '0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30)',
        'm3-2': '0px 2px 6px 2px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30)',
        'm3-3': '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)',
        'm3-4': '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)',
        'm3-5': '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)',
      },
      fontFamily: {
        sans: ['Roboto', 'Google Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
