"""Populate comprehensive high-quality Korean translations for NamiFAX."""

from __future__ import annotations

import os
from babel.messages import pofile, mofile

KO_TRANSLATIONS: dict[str, str] = {
    # Navigation & General
    "Inbox": "받은 팩스함",
    "Send Fax": "팩스 보내기",
    "Outbox": "보낸 팩스함",
    "Archive": "보관함",
    "Contacts": "연락처",
    "Address Book": "주소록",
    "Distribution Lists": "배포 그룹",
    "Email Book": "이메일 주소록",
    "Email Addresses": "이메일 주소록",
    "Settings": "환경설정",
    "Logout": "로그아웃",
    "Admin": "관리자",
    "User Portal": "사용자 포털",
    "Dashboard": "대시보드",
    "Home": "홈",

    # Auth & Account
    "Sign in": "로그인",
    "Sign in to your account": "계정에 로그인하세요",
    "Sign In": "로그인",
    "Username": "사용자 이름",
    "Password": "비밀번호",
    "Current Password": "현재 비밀번호",
    "New Password": "새 비밀번호",
    "Confirm New Password": "새 비밀번호 확인",
    "Forgot password?": "비밀번호를 잊으셨습니까?",
    "Lost Password Recovery": "비밀번호 찾기",
    "Send Reset Link": "재설정 링크 전송",
    "Password Expired": "비밀번호 만료",
    "Please update your password to continue.": "계속하려면 비밀번호를 변경해 주세요.",
    "Update Password": "비밀번호 변경",
    "Back to Login": "로그인 화면으로 돌아가기",
    "Remember me": "로그인 상태 유지",

    # Common Actions & Buttons
    "View": "보기",
    "PDF": "PDF",
    "TIFF": "TIFF",
    "Reply": "회신",
    "Reply to FAX": "팩스 회신",
    "Delete": "삭제",
    "Permanently delete": "영구 삭제",
    "Rotate": "회전",
    "Rotate Fax": "팩스 회전",
    "Search": "검색",
    "Reset": "초기화",
    "Cancel": "취소",
    "Save": "저장",
    "Save Changes": "변경사항 저장",
    "Send": "전송",
    "Edit": "편집",
    "Retry": "재시도",
    "Close": "닫기",
    "Download": "다운로드",
    "Download PDF": "PDF 다운로드",
    "Download TIFF": "TIFF 다운로드",
    "Upload": "업로드",
    "Import": "가져오기",
    "Export": "내보내기",
    "Refresh": "새로고침",
    "Clear": "지우기",
    "Back": "뒤로",
    "Filter": "필터링",
    "Apply": "적용",
    "Actions": "작업",
    "Status": "상태",
    "Details": "상세정보",
    "Preview": "미리보기",
    "Print": "인쇄",
    "Forward": "전달",
    "Assign": "지정",
    "Note": "메모",
    "Add Note": "메모 추가",
    "Email Fax": "이메일로 팩스 전송",
    "Assign Company": "회사 지정",
    "Resend Fax": "팩스 재전송",
    "Delete Fax": "팩스 삭제",
    "Transmission Report": "전송 보고서",

    # Common Table Headers & Labels
    "Date": "날짜",
    "Date & Time": "일시",
    "Start Date": "시작일",
    "End Date": "종료일",
    "From": "발신",
    "To": "수신",
    "Pages": "페이지 수",
    "Size": "크기",
    "Type": "유형",
    "Company": "회사",
    "Company Name": "회사명",
    "Company / Name": "회사명 / 수신자",
    "New Company": "새 회사 추가",
    "Add First Contact": "첫 번째 연락처 추가",
    "Edit Company": "회사 정보 편집",
    "Add New Company": "새 회사 추가",
    "Contact Name": "담당자명",
    "Email": "이메일",
    "Email Address": "이메일 주소",
    "Fax Number": "팩스 번호",
    "Voice Telephone": "전화번호",
    "Telephone": "전화번호",
    "Street Address": "상세 주소",
    "City / Postal Region": "도시 / 우편번호",
    "Category": "카테고리",
    "Category Tag": "카테고리 태그",
    "General": "일반",
    "Invoices & Billing": "청구서 및 정산",
    "Legal": "법무",
    "Description": "설명",
    "Description / Internal Notes": "설명 / 내부 메모",
    "Modem": "모뎀",
    "Modem Device": "모뎀 장치",
    "Port": "포트",
    "Device": "장치",
    "Priority": "우선순위",
    "Normal": "보통",
    "High": "높음",
    "Low": "낮음",
    "Resolution": "해상도",
    "Fine": "정밀",
    "Standard": "표준",

    # Send Fax Form
    "Destination & Recipients": "수신처 및 수신자 정보",
    "Destination Number": "수신 팩스 번호",
    "Enter the fax number and recipient details.": "팩스 번호 및 수신자 정보를 입력하세요.",
    "Fill in the details below and click Send.": "아래 세부 정보를 입력하고 전송 버튼을 누르세요.",
    "Attention To": "수신자명",
    "Subject / Regarding": "제목 / 용건",
    "Cover Page": "표지(Cover Page)",
    "Use cover page": "표지 사용",
    "Select Cover Page": "표지 템플릿 선택",
    "Comments / Notes": "메모 / 전달 내용",
    "Document Attachment": "문서 첨부",
    "Upload Document": "문서 업로드",
    "Supported formats: PDF, TIFF, PostScript, TXT": "지원 형식: PDF, TIFF, PostScript, TXT",
    "Drag & drop file here or click to browse": "파일을 여기로 드래그하거나 클릭하여 선택하세요",
    "File": "파일",
    "optional": "선택 사항",
    "required": "필수",
    "Send Options": "전송 옵션",
    "Schedule Transmission": "예약 전송",
    "Send Immediately": "즉시 전송",
    "Notification Email": "알림 이메일",
    "Notify on Completion": "완료 시 이메일 알림 수신",
    "To send to multiple recipients at once, separate numbers with a comma.": "여러 수신자에게 동시에 보내려면 번호를 쉼표로 구분하세요.",
    "Saved contacts are available in the": "저장된 연락처는 다음에서 선택할 수 있습니다:",

    # Inbox & Fax Viewing
    "Received Faxes": "수신된 팩스 목록",
    "All incoming faxes received across all active modem channels.": "모든 활성 모뎀 채널을 통해 수신된 팩스 내역입니다.",
    "No faxes in inbox": "받은 팩스가 없습니다",
    "Faxes received by your modems will appear here automatically.": "모뎀을 통해 수신된 팩스가 여기에 자동으로 표시됩니다.",
    "Select All": "전체 선택",
    "Deselect All": "전체 해제",
    "Delete Selected": "선택 항목 삭제",
    "Move Selected to Archive": "선택 항목 보관함으로 이동",
    "Page 1 of": "페이지: 1 /",
    "Fax Viewer": "팩스 뷰어",
    "Viewing Fax": "팩스 열람",
    "Incoming Fax": "수신 팩스",
    "Sent Fax": "발신 팩스",

    # Outbox
    "Transmission Queue & Spool": "전송 대기열 및 스풀",
    "Monitor active and queued outgoing transmissions.": "발신 대기 및 전송 중인 팩스 상태를 실시간으로 확인합니다.",
    "Queued Faxes": "대기 중인 팩스",
    "Completed Transmissions": "전송 완료 내역",
    "No faxes currently in queue": "현재 대기 중인 팩스가 없습니다",
    "Faxes being transmitted or queued will appear here.": "전송 중이거나 대기 중인 팩스가 여기에 표시됩니다.",
    "Job ID": "작업 ID",
    "Recipient": "수신자",
    "Attempts": "시도 횟수",
    "Kill Job": "작업 취소",
    "Alter Job": "작업 속성 수정",

    # Archive
    "Fax Archive Search": "팩스 보관함 검색",
    "Search historical incoming and outgoing faxes by date range, company, category, or keyword.": "날짜 범위, 회사, 카테고리 또는 키워드로 수발신 팩스 이력을 검색합니다.",
    "Search Criteria": "검색 조건",
    "Date Range": "기간",
    "All Categories": "모든 카테고리",
    "All Modems": "모든 모뎀",
    "Keyword": "키워드",
    "Search Archives": "보관함 검색",
    "Reset Search": "검색 초기화",
    "Archive Results": "보관함 검색 결과",
    "No faxes matched the search criteria": "검색 조건과 일치하는 팩스가 없습니다",
    "Try adjusting your filters, date range, or keywords.": "필터, 기간 또는 키워드를 변경해 보세요.",

    # Contacts & Distribution Lists
    "Save frequently used fax numbers for quick access when sending.": "자주 사용하는 팩스 번호를 저장하여 전송 시 빠르게 선택하세요.",
    "No contacts yet": "등록된 연락처가 없습니다",
    "No contacts matched": "일치하는 연락처가 없습니다",
    "Add contacts to quickly select fax numbers when sending without typing them every time.": "연락처를 등록하면 매번 입력할 필요 없이 빠르게 팩스를 보낼 수 있습니다.",
    "Distribution Group Management": "배포 그룹 관리",
    "Create and manage groups of recipients for mass fax dispatches.": "대량 팩스 발송을 위한 수신자 그룹을 생성하고 관리합니다.",
    "New Distribution List": "새 배포 그룹",
    "Create New List": "새 그룹 생성",
    "Group Name": "그룹명",
    "Members Count": "구성원 수",
    "Members": "구성원 목록",
    "Add Recipients": "수신자 추가",
    "Configure corporate contact identity and transmission routing defaults.": "회사 연락처 정보 및 팩스 수신 라우팅 기본값을 구성합니다.",
    "Back to Contacts": "연락처 목록으로 돌아가기",
    "Primary Company Profile": "기본 회사 프로필",
    "Recipient Contact & Physical Address": "수신자 담당자 및 주소 정보",
    "Attention Person": "담당자",

    # Modals
    "Send Fax via Email": "이메일로 팩스 전송",
    "Forward this fax as a PDF attachment to an email address.": "이 팩스를 PDF 첨부 파일로 이메일 주소에 전달합니다.",
    "Recipient Email": "수신 이메일",
    "Subject": "제목",
    "Message": "내용",
    "Send Email": "이메일 전송",
    "Add / Edit Fax Note": "팩스 메모 추가 / 편집",
    "Attach an internal note or description to this fax.": "이 팩스에 내부 메모나 설명을 첨부합니다.",
    "Save Note": "메모 저장",
    "Confirm Deletion": "삭제 확인",
    "Are you sure you want to permanently delete this fax? This action cannot be undone.": "이 팩스를 영구적으로 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.",
    "Yes, Delete": "예, 삭제합니다",
    "Assign Company to Fax": "팩스에 회사 지정",
    "Link this fax to a registered company in the address book.": "이 팩스를 주소록의 등록된 회사와 연결합니다.",
    "Select Company": "회사 선택",
    "Assign and Save": "지정 및 저장",
    "Resend Fax Transmission": "팩스 재전송",
    "Re-queue this fax for delivery to a new or corrected destination number.": "새로운 또는 수정된 수신 번호로 이 팩스를 다시 전송 대기열에 추가합니다.",
    "Resend Now": "지금 재전송",
    "Transmission Details": "전송 세부 정보",

    # Admin Dashboard & Console
    "Administration Console": "시스템 관리자 콘솔",
    "System Overview & Telemetry": "시스템 개요 및 텔레메트리",
    "Dashboard Overview": "대시보드 개요",
    "SYSTEM OPERATIONAL": "시스템 정상 운영 중",
    "Real-time status of fax spools, hardware serial modems, and registered users": "팩스 스풀, 하드웨어 시리얼 모뎀 및 등록된 사용자의 실시간 상태",
    "Active Users": "활성 사용자",
    "Configured Modems": "구성된 모뎀",
    "Spool Queue": "스풀 대기열",
    "Total Transmissions": "총 전송 건수",
    "System Services": "시스템 서비스",
    "Server Health": "서버 상태",
    "HylaFAX Daemon": "HylaFAX 데몬",
    "Database Engine": "데이터베이스 엔진",
    "Scheduler Service": "스케줄러 서비스",
    "User Accounts": "사용자 계정 관리",
    "Fax Modems": "팩스 모뎀 장치",
    "DID Routing": "DID 수신 라우팅",
    "Fax Categories": "팩스 카테고리 관리",
    "Cover Pages": "표지 템플릿 관리",
    "Barcode Routing": "바코드 라우팅",
    "Blacklist (DynConf)": "동적 차단 목록(DynConf)",
    "Fax to Email": "팩스-이메일 라우팅",
    "System Audit Logs": "시스템 감사 로그",
    "System Functions": "시스템 기능",

    # Admin Management Pages
    "Manage system users, login credentials, and interface roles.": "시스템 사용자, 로그인 자격 증명 및 권한 역할을 관리합니다.",
    "Create User": "사용자 생성",
    "Role": "역할",
    "Superuser": "최고 관리자",
    "Administrator": "관리자",
    "Standard User": "일반 사용자",
    "Permissions": "권한",
    "Can Send Fax": "팩스 발신 권한",
    "Can View Archive": "보관함 열람 권한",
    "Can Manage Settings": "설정 관리 권한",
    "Hardware Modem Configuration": "하드웨어 모뎀 구성",
    "Manage serial TTY and virtual modem ports connected to HylaFAX.": "HylaFAX에 연결된 시리얼 TTY 및 가상 모뎀 포트를 관리합니다.",
    "Modem Port": "모뎀 포트",
    "Device Node": "장치 노드",
    "Dial Command": "다이얼 명령",
    "Add Modem": "모뎀 추가",
    "DID / DTMF Route Groups": "DID / DTMF 수신 라우팅 그룹",
    "Route incoming faxes to specific users or email addresses by dialed number.": "수신 다이얼 번호(DID)를 기준으로 특정 사용자나 이메일 주소로 팩스를 라우팅합니다.",
    "DID / Route Code": "DID / 라우팅 코드",
    "Target Recipient": "수신 대상",
    "Add DID Route": "DID 라우팅 추가",
    "Barcode Routing Rules": "바코드 라우팅 규칙",
    "Route faxes automatically using barcodes detected on incoming cover sheets.": "수신된 표지에서 감지된 바코드를 기준으로 팩스를 자동 라우팅합니다.",
    "Barcode Pattern": "바코드 패턴",
    "Add Barcode Rule": "바코드 규칙 추가",
    "Dynamic Configuration & Blacklist": "동적 구성 및 차단 목록",
    "Block malicious callers and reject unwanted incoming fax transmissions.": "스팸 발신 번호를 차단하고 원치 않는 팩스 수신을 거부합니다.",
    "Caller ID (TSI)": "발신자 번호 (TSI)",
    "Block Rule": "차단 규칙",
    "Add Blacklist Rule": "차단 규칙 추가",
    "Fax to Email Forwarding": "팩스-이메일 자동 전달",
    "Automatically forward received faxes to designated corporate email inboxes.": "수신된 팩스를 지정된 회사 이메일 수신함으로 자동 전달합니다.",
    "Add Forwarding Rule": "전달 규칙 추가",
    "Audit Log Viewer": "감사 로그 뷰어",
    "Filter system access events, user operations, and transmission errors.": "시스템 접근 이벤트, 사용자 작업 및 전송 오류 로그를 필터링하여 확인합니다.",
    "All Severity Levels": "모든 심각도",
    "Info": "정보",
    "Warning": "경고",
    "Error": "오류",
    "Critical": "치명적",
    "System Operations & Maintenance": "시스템 작업 및 유지보수",
    "Reboot Services": "서비스 재시작",
    "Shutdown Services": "서비스 종료",
    "Download Archive": "보관함 다운로드",
    "Download Database": "데이터베이스 다운로드",
    "Perform administrative maintenance tasks on HylaFAX services and databases.": "HylaFAX 서비스 및 데이터베이스에 대한 관리 유지보수 작업을 수행합니다.",

    # Settings
    "User Preferences & Configuration": "사용자 환경설정 및 구성",
    "Customize language, time zone, display options, and account credentials.": "언어, 시간대, 화면 표시 옵션 및 계정 자격 증명을 설정합니다.",
    "Display Language": "표시 언어",
    "Select your preferred interface language.": "인터페이스에서 사용할 기본 언어를 선택하세요.",
    "Time Zone": "시간대",
    "Rows per Page": "페이지당 행 수",
    "Theme": "테마",
    "Light": "라이트 모드",
    "Dark": "다크 모드",
    "System Default": "시스템 기본값",
    "Notification Preferences": "알림 설정",
    "Receive email notifications when incoming faxes arrive": "새 팩스 수신 시 이메일 알림 받기",
    "Receive email notifications for sent faxes": "팩스 발신 결과 이메일 알림 받기",
    "Change Password": "비밀번호 변경",
    "Ensure your account is using a long, random password to stay secure.": "보안을 위해 길고 안전한 비밀번호를 사용하세요.",
    "Language updated successfully": "언어 설정이 성공적으로 업데이트되었습니다",
    "Password changed successfully": "비밀번호가 성공적으로 변경되었습니다",
    "Settings saved successfully": "설정이 성공적으로 저장되었습니다",

    # Admin Counters & Cards
    "Users": "사용자",
    "Modems": "모뎀",
    "DID Routes": "DID 라우팅",
    "Logs": "로그",
    "Fax Lines": "팩스 회선",
    "Hardware Ready": "하드웨어 준비 완료",
    "Active accounts": "활성 계정",
    "Backend Core": "백엔드 코어",
    "Scheduler": "스케줄러",
    "Running": "실행 중",
    "Registered User Accounts": "등록된 사용자 계정",
    "Manage Users": "사용자 관리",
    "Name": "이름",
    "Last Login": "마지막 로그인",
    "Server Status": "서버 상태",
    "Core": "코어",
    "System Scheduler": "시스템 스케줄러",
    "Administrator Workflow Guide": "관리자 워크플로우 가이드",

    # Admin Barcodes
    "Configure Barcode Routing": "바코드 라우팅 설정",
    "Route incoming faxes automatically based on recognized Code39 / QR barcodes": "인식된 Code39 / QR 바코드를 기준으로 수신 팩스를 자동 라우팅합니다.",
    "New Barcode Route": "새 바코드 라우트",
    "Barcode:": "바코드:",
    "Contact:": "연락처:",
    "None": "없음",
    "-- None --": "-- 없음 --",
    "Printer:": "프린터:",
    "Edit Barcode Route": "바코드 라우트 편집",
    "Add Barcode Route": "바코드 라우트 추가",
    "EDIT MODE": "편집 모드",
    "NEW": "신규",
    "Barcode": "바코드",
    "Alias": "별칭",
    "Contact Email": "연락처 이메일",
    "Printer": "프린터",

    # Admin Categories
    "Manage classification tags and archival categories for organizing transmissions": "팩스 전송 내역 정리를 위한 분류 태그 및 보관 카테고리를 관리합니다.",
    "New Category": "새 카테고리",
    "Existing Categories": "등록된 카테고리",
    "Edit Category": "카테고리 편집",
    "Add Category": "카테고리 추가",
    "Category Name": "카테고리명",

    # Admin Covers
    "Configure Cover Pages": "표지 템플릿 설정",
    "Manage facsimile PostScript cover page templates and layouts": "팩스 PostScript 표지 템플릿 및 레이아웃을 관리합니다.",
    "New Cover Page": "새 표지 템플릿",
    "Available Cover Pages": "사용 가능한 표지 목록",
    "Edit Cover Page": "표지 템플릿 편집",
    "Add Cover Page": "표지 템플릿 추가",
    "Title": "제목",

    # Admin Dynconf & Blacklist
    "Dynamic Configuration": "동적 구성(DynConf)",
    "Manage Caller ID blacklists and transmission rejection rules for modem devices": "모뎀 장치의 발신자 번호 차단 목록 및 수신 거부 규칙을 관리합니다.",
    "New Rule": "새 규칙",
    "Blocked Caller IDs": "차단된 발신자 번호",
    "Caller ID:": "발신자 번호:",
    "All Devices": "모든 장치",
    "Edit Caller ID Rule": "발신자 차단 규칙 편집",
    "Add Caller ID Rule": "발신자 차단 규칙 추가",
    "Caller ID": "발신자 번호",

    # Admin Fax2Email
    "Configure automated inbound fax forwarding and PDF dispatch rules mapped by company": "회사별 수신 팩스 자동 전달 및 PDF 발송 규칙을 구성합니다.",
    "Company Forwarding Rules": "회사별 전달 규칙",
    "Email:": "이메일:",
    "Edit Forwarding Rule": "전달 규칙 편집",

    # Admin Layout & Modems
    "Control Panel": "제어판",
    "Overview": "개요",
    "Access Control": "접근 제어",
    "Hardware & Lines": "하드웨어 및 회선",
    "Inbound Routing": "수신 라우팅",
    "Content & Templates": "콘텐츠 및 템플릿",
    "Security & System": "보안 및 시스템",
    "Admin Control Panel": "관리자 제어판",
    "Appliance Engine Online": "어플라이언스 엔진 정상 가동 중",
    "Configure Modems hardware devices, physical serial ports, and print-forwarding rules": "모뎀 하드웨어 장치, 물리 시리얼 포트 및 인쇄 전달 규칙을 설정합니다.",
    "Configure Modems": "모뎀 설정",
    "Active Modem Lines": "활성 모뎀 회선",
    "Contact": "연락처",
    "Edit Modem": "모뎀 편집",
    "Configure Modems Device": "모뎀 장치 설정",
    "Save Modem": "모뎀 설정 저장",
    "Appliance Note:": "어플라이언스 안내:",
    "Modems configured here must correspond to physical RS-232 serial devices, USB modems, or virtual IAX modems recognized by the underlying HylaFAX server.": "여기서 구성하는 모뎀은 HylaFAX 서버가 인식하는 물리 RS-232 시리얼 장치, USB 모뎀 또는 가상 IAX 모뎀과 일치해야 합니다.",

    # Admin DID Routing
    "Configure DID Routing": "DID 라우팅 설정",
    "Route incoming faxes by Direct Inward Dialing (DID) extension to specific email boxes or printers": "수신 다이얼(DID) 내선 번호를 기준으로 특정 이메일 수신함이나 프린터로 팩스를 라우팅합니다.",
    "New DID Route": "새 DID 라우트",
    "Active DID Routing Rules": "활성 DID 라우팅 규칙",
    "Route Code": "라우트 코드",
    "Action": "작업",
    "Configure Routing Rule": "라우팅 규칙 설정",
    "DID (Direct Inward Dialing) routing automatically redirects incoming transmissions matching extension patterns directly to mapped operator inboxes or physical printers.": "DID(Direct Inward Dialing) 라우팅은 내선 번호 패턴과 일치하는 수신 팩스를 매핑된 담당자 수신함이나 프린터로 직접 자동 전달합니다.",

    # Admin Sysfunc
    "Perform maintenance operations, service control, and backups.": "유지보수 작업, 서비스 제어 및 백업을 수행합니다.",
    "HylaFAX Engine Active": "HylaFAX 엔진 가동 중",
    "Admin Dashboard": "관리자 대시보드",
    "Caution: Appliance Maintenance Operations": "주의: 어플라이언스 유지보수 작업",
    "Restarting or shutting down services will interrupt active fax modem spooling and disconnect client sessions. Ensure all outbound transmissions in the modem queue are completed before initiating maintenance tasks.": "서비스를 재시작하거나 종료하면 진행 중인 팩스 모뎀 스풀링이 중단되고 클라이언트 세션 연결이 끊어집니다. 유지보수 작업을 시작하기 전에 모뎀 대기열의 모든 발신 전송이 완료되었는지 확인하십시오.",
    "Daemon Service Control": "데몬 서비스 제어",
    "Restart HylaFAX and NamiFAX web services, or halt background workers.": "HylaFAX 및 NamiFAX 웹 서비스를 재시작하거나 백그라운드 워커를 중지합니다.",
    "Database & Archive Backup": "데이터베이스 및 보관함 백업",
    "Download system archives and database snapshots for offsite retention.": "외부 보관을 위해 시스템 보관함 및 데이터베이스 스냅샷을 다운로드합니다.",

    # Admin Logs
    "System Logs": "시스템 로그",
    "Audit logs and HylaFAX server operational event traces": "감사 로그 및 HylaFAX 서버 운영 이벤트 추적 내역",
    "Keywords:": "키워드:",
    "Date:": "날짜:",
    "Log Text": "로그 내용",
    "No system logs found matching criteria.": "조건과 일치하는 시스템 로그가 없습니다.",
    "Transmissions and server events will be streamed here in real time.": "전송 내역 및 서버 이벤트가 여기에 실시간으로 스트리밍됩니다.",

    # Admin Users
    "Manage system operator credentials, access permissions, and route mapping": "시스템 운영자 자격 증명, 접근 권한 및 라우트 매핑을 관리합니다.",
    "Create New User": "새 사용자 생성",
    "YES": "예",
    "NO": "아니오",
    "Configure User:": "사용자 설정:",
    "Full Name": "전체 이름",
    "Permissions & Capabilities": "권한 및 기능",
    "Administrator Console": "관리자 콘솔",
    "Superuser Rights": "최고 관리자 권한",
    "Can Delete Faxes": "팩스 삭제 권한",
    "Send on Any Modem": "모든 모뎀 발신 권한",
    "Categories": "카테고리",

    # Archive
    "Archive Search": "보관함 검색",
    "Search all sent and received fax records by date, company, or fax number.": "날짜, 회사 또는 팩스 번호별로 수발신 팩스 기록을 검색합니다.",
    "results": "건의 결과",
    "result": "건의 결과",
    "Search Filters": "검색 필터",
    "Leave filters empty to search all records. Narrow results by adding more criteria.": "필터를 비워두면 전체 기록을 검색합니다. 조건을 추가하여 검색 결과를 좁힐 수 있습니다.",
    "Invoices / Orders": "청구서 / 발주서",
    "Legal / Contracts": "법무 / 계약서",
    "From Date": "시작 날짜",
    "To Date": "종료 날짜",
    "Direction": "구분",
    "Sent & Received": "수신 및 발신 전체",
    "Received only": "수신 팩스만",
    "Sent only": "발신 팩스만",
    "Fax ID": "팩스 ID",
    "Results": "검색 결과",
    "records": "건의 기록",
    "record": "건의 기록",
    "Sender": "발신자",
    "Re-send": "재전송",
    "No results found": "검색 결과가 없습니다",
    "Try adjusting your search terms or date range.": "검색어나 날짜 범위를 조정해 보세요.",
    "Reset filters": "필터 초기화",
    "Search the Archive": "보관함 검색",
    "Enter a keyword or filter above and click Search to find fax records.": "키워드나 필터를 입력하고 검색 버튼을 누르면 팩스 기록을 찾을 수 있습니다.",

    # Distrolist
    "Organize recipient groups for mass fax broadcasting and notifications.": "대량 팩스 동보 발송 및 알림을 위한 수신자 그룹을 구성합니다.",
    "Create List": "그룹 생성",
    "Saved Distribution Lists": "저장된 배포 그룹",
    "members": "명의 구성원",
    "Group Members & Settings": "그룹 구성원 및 설정",
    "Create New Distribution List": "새 배포 그룹 생성",
    "List Name": "그룹명",
    "Group Members (Contacts & Fax Numbers)": "그룹 구성원 (연락처 및 팩스 번호)",
    "contacts assigned": "개의 연락처 지정됨",
    "Remove": "삭제",
    "No contacts assigned to this list yet.": "아직 이 그룹에 지정된 연락처가 없습니다.",
    "Add Member": "구성원 추가",
    "Delete List": "그룹 삭제",
    "Edit Distribution List": "배포 그룹 편집",
    "Create Distribution List": "배포 그룹 생성",
    "Configure broadcast list parameters and recipient group members.": "동보 발송 그룹 파라미터 및 수신자 그룹 구성원을 설정합니다.",
    "Back to Lists": "그룹 목록으로 돌아가기",
    "Distribution List Profile": "배포 그룹 프로필",
    "Enrolled Members": "등록된 구성원",
    "List ID:": "그룹 ID:",
    "No contacts in this list.": "이 그룹에 연락처가 없습니다.",

    # Emailbook
    "Email Address Book": "이메일 주소록",
    "Manage email recipients, transmission routing, and contacts directory.": "이메일 수신자, 전송 라우팅 및 연락처 디렉터리를 관리합니다.",
    "New Contact": "새 연락처",
    "recipients": "명의 수신자",
    "Company Affiliation": "소속 회사",
    "No email contacts found in the directory. Click \"+ New Contact\" to register one.": "디렉터리에 이메일 연락처가 없습니다. \"+ 새 연락처\"를 클릭하여 등록하세요.",
    "Email Book - Edit Email Contact": "이메일 주소록 - 이메일 연락처 편집",
    "Manage contact information and company affiliation in Email Book.": "이메일 주소록에서 연락처 정보 및 소속 회사를 관리합니다.",
    "Back to Email Book": "이메일 주소록으로 돌아가기",
    "Contact Profile Details": "연락처 프로필 세부정보",

    # Auth & Login
    "Lost Password": "비밀번호 찾기",
    "Account Recovery Assistance": "계정 복구 지원",
    "Please enter your registered username or email address below. Password reset instructions will be dispatched to your account email address.": "등록된 사용자 이름 또는 이메일 주소를 입력하세요. 비밀번호 재설정 안내가 등록된 이메일로 발송됩니다.",
    "Username or Email Address": "사용자 이름 또는 이메일 주소",
    "Reset Password": "비밀번호 재설정",
    "Received faxes appear here automatically in real time.": "수신된 팩스가 여기에 실시간으로 자동 표시됩니다.",
    "Faxes": "팩스",
    "Fax": "팩스",
    "Archive Selected": "선택 항목 보관",
    "Showing": "표시 중:",
    "of": "/",
    "Select": "선택",
    "Received": "수신일시",
    "faxes": "개의 팩스",
    "0 FAXES": "0건의 팩스",
    "There are no incoming faxes waiting in your inbox. Incoming transmissions will automatically appear here in real time.": "받은 팩스함에 대기 중인 수신 팩스가 없습니다. 새로 수신되는 팩스는 실시간으로 자동 표시됩니다.",
    "Send Your First Fax": "첫 번째 팩스 보내기",
    "Search Archive": "보관함 검색",
    "Getting Started with NamiFAX": "NamiFAX 시작하기",
    "Receive Faxes": "팩스 수신",
    "When someone sends a fax to this system's number, it will appear here automatically.": "팩스 번호로 팩스가 전송되면 여기에 자동으로 표시됩니다.",
    "Send Faxes": "팩스 발신",
    "Click Send Fax to transmit a PDF or image document to any fax number.": "팩스 보내기를 클릭하여 PDF나 이미지 문서를 원하는 팩스 번호로 전송하세요.",
    "Manage Records": "기록 관리",
    "Download faxes as PDF, archive them for later, or search all records in the Archive.": "팩스를 PDF로 다운로드하거나 나중에 볼 수 있도록 보관하고, 보관함에서 모든 기록을 검색할 수 있습니다.",
    "Enter your credentials to continue.": "계속하려면 자격 증명을 입력하세요.",
    "System Online": "시스템 온라인",
    "Contact your system administrator if you need an account.": "계정이 필요하시면 시스템 관리자에게 문의하세요.",
    "Login": "로그인",

    # Modals & Dialogs
    "Assign Company Name": "회사명 지정",
    "Associate document with registered enterprise contact": "문서를 등록된 기업 연락처와 연결합니다.",
    "Search Company Name": "회사명 검색",
    "Select Contact Record": "연락처 선택",
    "Are you sure you want to delete this fax?": "이 팩스를 삭제하시겠습니까?",
    "This operation will permanently purge the fax document archive.": "이 작업은 팩스 문서 보관 파일을 영구적으로 삭제합니다.",
    "Dispatch PDF document attachment to email recipients": "PDF 문서 첨부 파일을 이메일 수신자에게 발송합니다.",
    "Recipients": "수신자",
    "Append internal administrative note or comments": "내부 관리 메모 또는 코멘트를 추가합니다.",
    "Note / Description": "메모 / 설명",
    "Reply to Fax": "팩스에 회신",
    "Dispatch quick reply transmission to originating sender": "발신자에게 빠른 회신 팩스를 발송합니다.",
    "Regarding (Subject)": "용건 (제목)",
    "Comments": "전달 내용",
    "Official facsimile delivery confirmation receipt": "공식 팩스 전송 확인증",
    "Company:": "회사:",
    "Pages:": "페이지 수:",
    "Status:": "상태:",
    "Transmitted Successfully (OK)": "정상 전송 완료 (OK)",

    # Outbox & Queue
    "Faxes currently queued or being transmitted.": "현재 대기 중이거나 전송 중인 팩스입니다.",
    "This page shows only faxes that are queued or in progress. Once delivered, they are removed from this list. Find completed records in the": "이 페이지에는 대기 중이거나 진행 중인 팩스만 표시됩니다. 전송이 완료되면 목록에서 제거되며 보관함에서 확인할 수 있습니다:",
    "jobs in progress": "건의 작업 진행 중",
    "job in progress": "건의 작업 진행 중",
    "Destination": "수신처",
    "Queued": "대기 등록 일시",
    "No jobs in queue": "대기 중인 작업 없음",
    "There are no faxes waiting to be sent. Send a fax to see its progress here.": "전송 대기 중인 팩스가 없습니다. 팩스를 보내면 진행 상황이 여기에 표시됩니다.",
    "Send a Fax": "팩스 보내기",
    "Failed Transmissions": "전송 실패 내역",
    "Review the number or retry below.": "번호를 확인하거나 아래에서 재시도하세요.",
    "Reason": "사유",

    # Pwdexpired
    "Security Credentials Renewal": "보안 자격 증명 갱신",
    "Action Required": "필수 조치 사항",
    "Your password has expired or needs to be changed before proceeding. Please enter your old password and choose a new password.": "비밀번호가 만료되었거나 계속 진행하기 전에 변경해야 합니다. 기존 비밀번호를 입력하고 새 비밀번호를 설정하세요.",
    "Old Password": "기존 비밀번호",

    # Sendfax Advanced
    "Attach the file you want to transmit.": "전송할 파일을 첨부하세요.",
    "Click to select a file": "클릭하여 파일 선택",
    "Supported: PDF, TIFF, PostScript, TXT · Max 10 MB": "지원 형식: PDF, TIFF, PostScript, TXT · 최대 10 MB",
    "PDF is the most commonly used format. Convert Word or Excel files to PDF before attaching.": "PDF가 가장 권장되는 형식입니다. Word나 Excel 파일은 PDF로 변환 후 첨부하세요.",
    "Add a cover sheet with sender and recipient info.": "발신자 및 수신자 정보가 포함된 표지를 추가합니다.",
    "Include Cover Page": "표지 포함",
    "Cover Template": "표지 템플릿",
    "Standard (Default)": "표준 (기본값)",
    "Urgent": "긴급",
    "Confidential": "기밀",
    "Send via Line": "발신 회선 선택",
    "Auto-select recommended": "자동 선택 권장",
    "Any Available Line (Auto)": "사용 가능한 모든 회선 (자동)",
    "Cover Comments": "표지 전달 내용",
    "Advanced Options": "고급 옵션",
    "Priority, retries, notifications": "우선순위, 재시도 횟수, 알림 설정",
    "High (Urgent)": "높음 (긴급)",
    "Max Retries": "최대 재시도 횟수",
    "Retries automatically on busy signal.": "통화 중일 경우 자동으로 재시도합니다.",
    "Notify on retry": "재시도 시 알림",
    "Cancel & return to Inbox": "취소하고 받은 팩스함으로 이동",

    # Settings
    "User Settings": "사용자 환경설정",
    "Configure your personal profile, fax station identity, and portal preferences.": "개인 프로필, 팩스 국선 식별 정보 및 포털 환경설정을 구성합니다.",
    "Return to Inbox": "받은 팩스함으로 돌아가기",
    "Personal & Organization Details": "개인 및 조직 세부 정보",
    "Office / Location": "사무실 / 위치",
    "Direct Voice Number": "직통 전화번호",
    "Direct Fax Number": "직통 팩스 번호",
    "Transmitting Station ID (TSI)": "발신 팩스 식별자 (TSI)",
    "Header identifier imprinted on top of transmitted fax pages.": "전송되는 팩스 페이지 상단에 인쇄되는 헤더 식별자입니다.",
    "Email & Fax Notification Signature": "이메일 및 팩스 알림 서명",
    "Portal & Delivery Preferences": "포털 및 수신 기본 설정",
    "Default Cover Page": "기본 표지 템플릿",
    "Faxes Per Page": "페이지당 팩스 수",
    "Update Settings": "설정 업데이트",

    # Viewfax & Details
    "FROM:": "발신:",
    "DATE:": "수신일시:",
    "DEVICE:": "장치:",
    "Prev": "이전",
    "Next": "다음",
    "Total": "전체",
    "Page": "페이지",
    "Incoming Transmission": "수신 팩스 전송",
    "FACSIMILE TRANSMISSION": "팩스 전송 내역",
    "Date Received:": "수신 일시:",
    "Originating Station:": "발신 국선 ID:",
    "PORT": "포트",
    "High-Resolution Raster Preview": "고해상도 래스터 미리보기",
    "Device Line:": "장치 회선:",
    "Download Original Document": "원본 문서 다운로드",
    "NamiFAX Enterprise Facsimile Engine": "NamiFAX 엔터프라이즈 팩스 엔진",
    "Archive ID:": "보관 ID:",
}


def populate_ko():
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    po_path = os.path.join(root_dir, "src", "namifax", "locale", "ko", "LC_MESSAGES", "namifax.po")
    mo_path = os.path.join(root_dir, "src", "namifax", "locale", "ko", "LC_MESSAGES", "namifax.mo")

    with open(po_path, "rb") as f:
        catalog = pofile.read_po(f)

    updated_count = 0
    for msg in catalog:
        if not msg.id:
            continue
        msg_id_str = msg.id if isinstance(msg.id, str) else msg.id[0]

        # Exact match in our rich dict
        if msg_id_str in KO_TRANSLATIONS:
            msg.string = KO_TRANSLATIONS[msg_id_str]
            if "fuzzy" in msg.flags:
                msg.flags.discard("fuzzy")
            updated_count += 1
        elif msg.string and "fuzzy" not in msg.flags:
            # Keep existing valid translation
            pass
        else:
            # Check lowercase / trimmed variations
            trimmed = msg_id_str.strip()
            if trimmed in KO_TRANSLATIONS:
                msg.string = KO_TRANSLATIONS[trimmed]
                if "fuzzy" in msg.flags:
                    msg.flags.discard("fuzzy")
                updated_count += 1

    with open(po_path, "wb") as f:
        pofile.write_po(f, catalog)

    with open(mo_path, "wb") as f:
        mofile.write_mo(f, catalog)

    print(f"Updated {updated_count} Korean translations in {po_path}")
    print(f"Compiled binary MO file at {mo_path}")


if __name__ == "__main__":
    populate_ko()
